# Generated by Django 5.1.1 on 2024-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('assignment_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete')], max_length=10)),
            ],
        ),
    ]
