# Generated by Django 5.1.1 on 2024-09-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='status',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student_name',
        ),
        migrations.AddField(
            model_name='homework',
            name='assignment_description',
            field=models.TextField(default=''),
        ),
    ]
