# Generated by Django 5.1.1 on 2024-09-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_remove_homework_class_name_remove_homework_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='assignment_description',
        ),
        migrations.AddField(
            model_name='homework',
            name='class_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
